name: test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run unit tests
        run: python -m unittest

      - name: Run integration tests
        run: |
          docker build -t queick-test .
          docker run --rm -it queick-test:latest 
